ERROR:root:Exception occurred: 
Traceback (most recent call last):
  File "c:\AD-Export-Tool\dashboard_window.py", line 191, in run_first_script
    self.insert_data_into_database1(conn, data)
  File "c:\AD-Export-Tool\dashboard_window.py", line 227, in insert_data_into_database1
    cursor.execute("""
sqlite3.OperationalError: table ad_computers has no column named AdditionalColumn
ERROR:root:Exception occurred: 
Traceback (most recent call last):
  File "c:\AD-Export-Tool\dashboard_window.py", line 191, in run_first_script
    self.insert_data_into_database1(conn, data)
  File "c:\AD-Export-Tool\dashboard_window.py", line 227, in insert_data_into_database1
    cursor.execute("""
sqlite3.OperationalError: table ad_computers has no column named AdditionalColumn
ERROR:root:Exception occurred: 
Traceback (most recent call last):
  File "c:\AD-Export-Tool\dashboard_window.py", line 191, in run_first_script
    self.insert_data_into_database1(conn, data)
  File "c:\AD-Export-Tool\dashboard_window.py", line 227, in insert_data_into_database1
    cursor.execute("""
sqlite3.OperationalError: table ad_computers has no column named AdditionalColumn
ERROR:root:Exception occurred: 
Traceback (most recent call last):
  File "c:\AD-Export-Tool\dashboard_window.py", line 191, in run_first_script
    self.insert_data_into_database1(conn, data)
  File "c:\AD-Export-Tool\dashboard_window.py", line 227, in insert_data_into_database1
    cursor.execute("""
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 17, and there are 18 supplied.
ERROR:root:Exception occurred: 
Traceback (most recent call last):
  File "c:\AD-Export-Tool\dashboard_window.py", line 191, in run_first_script
    self.insert_data_into_database1(conn, data)
  File "c:\AD-Export-Tool\dashboard_window.py", line 227, in insert_data_into_database1
    cursor.execute("""
sqlite3.OperationalError: table ad_computers has no column named AdditionalColumn
